name: Release with goreleaser
on:
  push:
    tags:
      - v*.*.*
jobs:
  build:
    runs-on: ubuntu-latest
    name: goreleaser
    steps:
    - uses: actions/checkout@v3
    - name: Unshallow Fetch
      run: git fetch --prune --unshallow
    - uses: actions/setup-go@v4
      with:
        go-version: '^1.20.6'
    - name: Release via goreleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        distribution: goreleaser
        args: release --release-notes=doc/whats_new.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # HOMEBREW: ${{ secrets.HOMEBREW }}